#!/bin/sh


if [ "$1" = "all" ]
then
rm kernel.img
make clean
make

nasm -f bin -o fs.img src/fs.asm

dd if=fs.img of=disk.img bs=512 count=262144 conv=notrunc
dd if=kernel.img of=disk.img bs=512 count=128 conv=notrunc
fi

if [ "$1" = "kernel" ]
then
rm kernel.img
make clean
make

dd if=kernel.img of=disk.img bs=512 count=128 conv=notrunc
fi

if [ "$1" = "fs" ]
then

nasm -f bin -o fs.img src/fs.asm

dd if=fs.img of=disk.img bs=512 count=262144 conv=notrunc
dd if=kernel.img of=disk.img bs=512 count=128 conv=notrunc
fi